replicaCount: 1
postgres:
  name: postgres-movie
  group: db
  container:
    image: postgres:latest
    port: 5432
  service:
    type: NodePort
    protocol: TCP
  volume:
    name: movie-storage
    kind: PersistentVolumeClaim
    mountPath: /var/lib/postgresql/data
    pvc:
      name: movie-db-pvc
      accessMode: ReadWriteMany
      storage: 5Gi
  config:
    name: postgres-config-movie
    data:
      - key: POSTGRES_DB
        value: movie_db_dev
      - key: POSTGRES_USER
        value: movie_db_username
      - key: POSTGRES_PASSWORD
        value: movie_db_password
